name: hotel
description: "RH POS"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  fl_chart: ^0.69.0
  win32: ^5.15.0
  ffi: ^2.1.4
  dio: ^5.9.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  # object box++
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0
  intl: ^0.20.2
  share_plus: ^12.0.1
  path: ^1.9.1
  path_provider: ^2.1.5
  uuid: ^4.5.1
  # object box--
  timezone: ^0.10.1
  flutter_local_notifications: ^19.5.0
  table_calendar: ^3.2.0
  mongo_dart: ^0.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  printing: ^5.14.2
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  pdf: ^3.11.3
  # object box++
  build_runner: ^2.4.11
  objectbox_generator: ^4.3.0
  # object box--

flutter:
  uses-material-design: true
  # assets/json/users.json
  assets:
    - assets/json/
    - assets/image/
#    - assets/rh.png
